import type { Metadata } from "next";
import LayoutProvider from "@/components/LayoutProvider";
import './globals.css'
import './../stylesheets/commonClasses.css'
import './../stylesheets/antdOveride.css'
import './../stylesheets/layout.css'
import './../stylesheets/loader.css'
import ReduxProvider from "@/components/ReduxProvider";

export const metadata: Metadata = {
  title: "Dashboard | Job Portal Nextjs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
        <LayoutProvider>{children}</LayoutProvider>
    </ReduxProvider>
  
  );
}
